### ISSUE TITLE
Option to toggle passing AccessToken vs idToken to backend

### ISSUE THREAD

**Issue by radicand** [dniel/traefik-forward-auth0#290]
Currently AccessToken is passed as the Authorization header to the backend, but applications like Kubernetes Dashboard will work OOB with an idToken. Is there a way to toggle (on a per-app basis) which JWT is passed to the backend?

**Comment by radicand** [comment]
Closing this issue, as I've worked out how to add the necessary claims to the accessToken in Auth0. For those that follow and are interested specifically in K8s Dashboard, or making the access token have more claims:

Create a rule similar to the below:

```js
function(user, context, callback) {
  const namespace = 'https://your.namespace/';
  context.accessToken[namespace + 'group'] = user.user_metadata.k8s_group;
  context.accessToken[namespace + 'email'] = user.email;
  callback(null, user, context);
}
```

This assumes you've also leveraged Auth0 user metadata to set a field called `k8s_group`.

Next, ensure your kube-apiserver has the right oauth parameters passed to it. In K3s, the config yaml would look like:

```yaml
# ...
kube-apiserver-arg:
  - "oidc-issuer-url=https://your-tenant.auth0.com/"
  - "oidc-client-id=https://your.auth0.API.clientId"
  - "oidc-username-claim=https://your.namespace/email"
  - "oidc-username-prefix=oidc:"
  - "oidc-groups-claim=https://your.namespace/group"
  - "oidc-groups-prefix=oidc:"
```
If you have multiple nodes, ensure this is configured the same on all of them.

Finally, create the CRB:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oidc-cluster-admins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: oidc:cluster_admin
```

Assuming your Auth0 user has the user metadata field `k8s_group: "cluster_admin"` set, and you've otherwise setup the middleware for this in front of K8s Dashboard properly, it should work just fine.
