### ISSUE TITLE
URL to service always shows /oauth2/signin?code=...

### ISSUE THREAD

**Issue by bigwheels16** [dniel/traefik-forward-auth0#48]
When I use traefik-forward-auth0, it will forward to Auth0 to login, and when it comes back it correctly shows the app I was trying to access.  However, the URL still includes the code from the Authorization Grant.  example: https://whoami.mydomain.com/oauth2/signin?code=JQSfySa7z-x...

That is the first problem.

I can keep refreshing the page and it will keep showing my app.  However, if I remove the extra parts of the URL, (if I navigate to https://whoami.mydomain.com), it then starts another Authorization Grant all over again.

That is the second problem.

Here is the docker-compose.yml I am using:

```
   traefik:
     image: traefik:v1.7.9-alpine
     ports:
       - 80:80
       - 443:443
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./traefik/traefik.toml:/traefik.toml
       - ./certs:/certs
 
   whoami:
     image: containous/whoami
     labels:
       - "traefik.frontend.rule=Host:whoami.mydomain.com"
       - "traefik.enable=true"
       - "traefik.port=80"
       - "traefik.frontend.auth.forward.address=https://auth.mydomain.com/authorize"
 
   auth:
     image: dniel/forwardauth
     labels:
       - "traefik.frontend.rule=Host:auth.mydomain.com"
       - "traefik.enable=true"
       - "traefik.port=8080"
     volumes:
       - ./traefik-forward-auth0/application.yaml:/config/application.yaml
```

And here is the application.yaml I am using:

```
 domain: https://mydomain.auth0.com/
 token-endpoint: https://mydomain.auth0.com/oauth/token
 authorize-url: https://mydomain.auth0.com/authorize
 
 default:
     name: mydomain.com
     client-id: <CLIENT_ID>
     client-secret: <CLIENT_SECRET>
     audience: https://mydomain.com
     scope: "profile openid email"
     redirect-uri: https://mydomain.com/oauth2callback2
     token-cookie-domain: mydomain.com
 
 apps:
   - name: whoami.mydomain.com
     redirect-uri: https://whoami.mydomain.com/oauth2/signin
     token-cookie-domain: whoami.mydomain.com
```

This is the version of the app from docker that I am using:
`dniel/forwardauth             latest                35c6c5153576        2 days ago          246MB`

**Comment by dniel** [comment]
@bigwheels16 thanx for the feedback 👍 
I will debug it and try to find out whats happening. You write that you see the correct website after signin, but the url contain the code from the Authorization Grant. That indicates that maybe traefik.toml is misconfigured, because it seems that ForwardAuth didnt receive the callback but instead your whoami directly without intercepting the signing requets in between. If ForwardAuth application had intercepted and validated your session you should see two cookies set in your browser, ACCESS_TOKEN and ID_TOKEN containing the validated tokens.

Could you send me a copy of your traefik.toml file, and I'll try to find out if thats the case.

**Comment by bigwheels16** [comment]
It's very possible.  Here is my traefik.toml file:

```
debug = false

sendAnonymousUsage = true

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.traefik]
  address = ":8081"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [entryPoints.https.tls.defaultCertificate]
      certFile = "/certs/fullchain.pem"
      keyFile = "/certs/privkey.pem"

[api]
entrypoint = "traefik"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "mydomain.com"
watch = true
exposedbydefault = false
```

**Comment by dniel** [comment]
I see that you have configured the ForwardAuth/authorize endpoint through traefik itself. Could you try to do figure it to go outside e.g.. http://localhost:8080/authorize instead? To see if change anything?

**Comment by dniel** [comment]
In the traefik.frontend.auth.forward.address line

**Comment by bigwheels16** [comment]
Thank you! I got it working.  I believe I misunderstood how forward auth worked in Traefik so this has helped clear it up.

For reference, this is the new docker-compose.yml:

```
   traefik:
     image: traefik:v1.7.9-alpine
     ports:
       - 80:80
       - 443:443
     volumes:
       - /var/run/docker.sock:/var/run/docker.sock
       - ./traefik/traefik.toml:/traefik.toml
       - ./certs:/certs
 
   whoami:
     image: containous/whoami
     labels:
       - "traefik.frontend.rule=Host:whoami.mydomain.com"
       - "traefik.enable=true"
       - "traefik.port=80"
       - "traefik.frontend.auth.forward.address=http://auth:8080/authorize"
 
   auth:
     image: dniel/forwardauth
     labels:
       - "traefik.frontend.rule=Host:auth.mydomain.com"
       - "traefik.enable=true"
       - "traefik.port=8080"
     volumes:
       - ./traefik-forward-auth0/application.yaml:/config/application.yaml
```

And this is the new application.yaml:

```
 domain: https://mydomain.auth0.com/
 token-endpoint: https://mydomain.auth0.com/oauth/token
 authorize-url: https://mydomain.auth0.com/authorize
 
 default:
     name: mydomain.com
     client-id: <CLIENT_ID>
     client-secret: <CLIENT_SECRET>
     audience: https://mydomain.com
     scope: "profile openid email"
     redirect-uri: https://mydomain.com/oauth2callback2
     token-cookie-domain: mydomain.com
 
 apps:
   - name: whoami.mydomain.com
     redirect-uri: https://auth.mydomain.com/signin
```

This uses the root domain for the cookie domain rather than the sub-domain, and it redirects to the auth service /signin rather than the individual service at /oauth2/signin, because I haven't yet figured out how to configure Traefik to do that.  But I'll try that next.
