### ISSUE TITLE
How to handle Authorization

### ISSUE THREAD

**Issue by bigwheels16** [dniel/traefik-forward-auth0#53]
Currently I have several apps running behind Apache using the mod_auth_openidc module that is configured to delegate authentication to Auth0, which is configured to delegate to Google.  So technically anybody with a Google account can successfully authenticate.  However, there are only a few users that should actually be able to access these apps.  The mod_auth_openidc module I am using lets me restrict access to only users that have specific claims in their id token, and using Auth0 rules (I am using the Auth0 authorization plugin) I can make sure those claims are only added for the users that I want to allow access.

Does this project have a way to achieve something similar to that?  Or any plan or desire to add that?

I am not necessarily looking for the same mechanism that the Apache module uses, but just some way to centrally manage and control authorization to services behind Traefik on a per-service and per-user basis.

**Comment by dniel** [comment]
Use Auth0 to perform authorization logic.
Auth0 "provide a universal authentication & authorization platform for web, mobile and legacy applications." as they say. Auth0 is very flexible on how to implement authorization. 

You could for example use [Rules](https://auth0.com/docs/rules) to create simple authorization logic, or you could combine Rules and the [Authorization Extension](https://auth0.com/docs/extensions/authorization-extension/v2) to create a more [complex logic.](https://auth0.com/docs/extensions/authorization-extension/v2/rules)

**Comment by dniel** [comment]
If you already have authorization logic in Auth0,  why not also block access with rules in Auth0 at the same time?

**Comment by dniel** [comment]
I checked how ForwardAuth handle when Auth0 responds with error=unauthorized 
Seems that it just bugs out with standard error handling #54 when it should have handled this nicer.
I'll have to fix that.

**Comment by bigwheels16** [comment]
Hmm, I guess I had never considered that.  I'm not sure how I feel about that considering this is an authorization concern and that would effectively be moving it to an authentication concern, but I'll give it a try and see how it works out.

**Comment by bigwheels16** [comment]
So I did get this to work by writing a rule in Auth0.  In a simple scenario, it works fine, but it's probably not sufficient for slightly more complex scenarios.

For instance, let's say I have app1.mydomain.com and app2.mydomain.com.  And then in Auth0 I have rules about who can login based on which app they are trying to access.  In the simple scenario, I set the cookie domain to app1.mydomain.com and app2.mydomain.com, respectively, and then I have to login once for each app I want to access.  So far so good.

Let's say that I decide that I don't want to have to login separately for each app.  So I set the cookie domain to mydomain.com.  This way I can login once, and then access all the apps.  And as long as access is all or nothing, all apps or no apps, the current setup works.  But if I want to give a user access to app1 but not app2, this won't work anymore because he could just login with app1, and then from there access app2.

It would be ideal, and also idiomatic OAuth2, to require a certain a "scope" in order to access a particular app.  For instance, the "app2:read" scope might be required to access app2.mydomain.com.

So I am suggesting an enhancement where you can specify a list of required scope within the yaml configuration that would grant access to the app (see the last two lines in the example below).  If this is something you are open to, I'd be willing to submit a PR with the changes, but I'd probably need you to point me to the place in the code where the check should go.

```
 domain: https://mydomain.auth0.com/
 token-endpoint: https://mydomain.auth0.com/oauth/token
 authorize-url: https://mydomain.auth0.com/authorize
 
 default:
     name: mydomain.com
     client-id: <CLIENT_ID>
     client-secret: <CLIENT_SECRET>
     audience: https://mydomain.com
     scope: "profile openid email"
     redirect-uri: https://mydomain.com/oauth2callback2
     token-cookie-domain: mydomain.com
 
 apps:
   - name: whoami.mydomain.com
     redirect-uri: https://whoami.mydomain.com/oauth2/signin
     token-cookie-domain: whoami.mydomain.com
     required-scopes:
       - whoami:read
```
